#!/bin/sh -ex
export OPAMJOBS=80
grep -v '^#' > /home/opam/PACKAGES
cd /home/opam
git -C /home/opam/opam-repository pull origin master && opam update -uy
opam pin add -n --dev odoc
opam --yes depext -uyi `cat PACKAGES`
opam exec -- odig odoc
tar -C `opam config var prefix`/var/cache/odig -jcf /home/opam/docs.tbz odoc/
git clone git://github.com/mirage/docs .gh-pages --reference .
git -C .gh-pages checkout --orphan gh-pages
git -C .gh-pages reset
git -C .gh-pages clean -dxf
cp -r ./odoc/* .gh-pages/
echo docs.mirage.io > .gh-pages/CNAME
git -C .gh-pages add .
git -C .gh-pages commit -m 'BuildKite Update'
git -C .gh-pages push origin gh-pages -f
rm -rf .gh-pages odoc
